# src/research_crew/config/tasks.yaml
research_task:
  description: >
    Conduct thorough research on company {company}. Focus on comparative financial analysis between 2025 and 2024. Specifically research:
    1. Current company status and health (2025)
    2. Key financial metrics comparison: 2025 vs 2024
       - Revenue growth year-over-year
       - Net income and profit margins
       - Earnings per share (EPS) comparison
       - Operating cash flow changes
       - Return on equity (ROE) and return on assets (ROA)
    3. Latest quarterly results and earnings reports (Q1-Q4 2025 vs Q1-Q4 2024)
    4. Stock performance and market capitalization changes (2025 vs 2024)
    5. Major business developments and strategic changes between 2024-2025
    6. Recent news and events (2025, latest available)
    7. Future outlook and analyst projections

    IMPORTANT: Search for specific terms like "{company} 2025 vs 2024 financial comparison", 
    "{company} revenue growth 2025 2024", "{company} earnings comparison year over year",
    "{company} financial metrics 2025 2024", and "{company} annual report 2025 2024".
    Make sure to organize your findings in a structured format with clear sections showing year-over-year comparisons.
  expected_output: >
    A comprehensive research document with well-organized sections covering
    all the requested aspects of {company}. Include specific facts, figures,
    and examples where relevant.
  agent: researcher

analysis_task:
  description: >
    Analyze the research findings and create a comprehensive report on {company}.
    Your report should:
    1. Begin with an executive summary
    2. Include all key information from the research
    3. Provide insightful analysis of trends and patterns
    4. Offer a market outlook for company, noting that this should not be used for trading decisions
    5. Be formatted in a professional, easy-to-read style with clear headings
  expected_output: >
    A polished, professional report on {company} that presents the research
    findings with added analysis and insights. The report should be well-structured
    with an executive summary, main sections, and conclusion.
  agent: analyst
  context:
    - research_task
  output_file: output/report.md
